# H2 Database
spring.datasource.url=jdbc:h2:mem:tasklistdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Access Token - 15 minutes
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000

# JWT Refresh Token - 7 days
jwt.refresh.secret=504E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
jwt.refresh.expiration=604800000

# App
server.port=8080